# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GD-Barcode-Code93
version:      1.2
version_from: lib/GD/Barcode/Code93.pm
installdirs:  site
requires:
    GD::Barcode:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
